inherit_gem:
  rubocop-rails-omakase:
    - rubocop.yml

Style/StringLiterals:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/EndAlignment:
  Enabled: false
